services:
  api:
    build: .
    ports:
      - '3001:3000'
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/magazine
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
