FROM golang:1.10

RUN go get github.com/revel/revel \
 && go get github.com/revel/cmd/revel \
 && go get github.com/revel/modules/orm/gorp \
 && go get github.com/revel/modules/static \
 && go get github.com/revel/modules/testrunner

