server:
  port: 9090
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    root: info
    org:
      hibernate: trace


# 로컬환경에서 h2-console 이 security 적용받지 않도록 적용
app:
  security:
    ignore: /h2-console/**

# Note.
#
# ` Database "mem:testdb" not found ` 에러가 발생 시 해야 할 일
# H2 버전 1.4.198 이상에서는 데이터베이스를 미리 생성하는 것을 방지하도록 설정
# spring.datasource.url 속성을 설정하면
# springboot 시작 시 해당 정보를 가지고
# Datasource 객체를 만들게 되어 이슈를 해결할 수 있음.
#
