"""Initial DB setup.

Revision ID: 9aa329ea9256
Revises:
Create Date: 2019-04-22 18:37:04.075777

"""

# revision identifiers, used by Alembic.
revision = "9aa329ea9256"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
