"""followers.

Revision ID: eb70668a123c
Revises: 17de12da1127
Create Date: 2019-04-28 16:52:49.975814

"""
from alembic import op
from sqlalchemy.dialects import postgresql

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "eb70668a123c"
down_revision = "17de12da1127"
branch_labels = None
depends_on = None


def upgrade():  # noqa: D103
    op.create_table(
        "followers",
        sa.Column(
            "follower_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "followed_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["followed_id"], ["users.id"], name=op.f("fk_followers_followed_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"], ["users.id"], name=op.f("fk_followers_follower_id_users")
        ),
    )


def downgrade():  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
