#!/bin/sh

#
# Refer to `.git/hooks/pre-push.sample` for more information about this hook script.
#

set -e

docker-compose rm -sf
docker-compose up -d mongodb
./gradlew clean all
docker-compose up -d --build
curl https://raw.githubusercontent.com/gothinkster/realworld/master/api/Conduit.postman_collection.json -o build/postman.json
newman run build/postman.json -e backend/src/test/resources/environment.json
newman run backend/src/test/resources/postman.json -e backend/src/test/resources/environment.json
sudo docker system prune -af
