spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realworld?serverTimezone=UTC
    username: realadmin
    password: realadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            format_sql: true
            use_sql_comments: true
            jdbc:
                lob:
                non_contextual_creation: true