module.exports = [
  {
    path: '/',
    exact: true,
    componentName: 'pages/home',
  }, {
    path: '/page/:page',
    exact: true,
    componentName: 'pages/home',
  }, {
    path: '/feed',
    exact: true,
    componentName: 'pages/home',
  }, {
    path: '/feed/page/:page',
    exact: true,
    componentName: 'pages/home',
  }, {
    path: '/tag/:tag',
    exact: true,
    componentName: 'pages/home',
  }, {
    path: '/tag/:tag/page/:page',
    exact: true,
    componentName: 'pages/home',
  }, {
    path: '/(author|favorited)/:author',
    exact: true,
    componentName: 'pages/profile',
  }, {
    path: '/(author|favorited)/:author/page/:page',
    exact: true,
    componentName: 'pages/profile',
  }, {
    path: '/new-post',
    exact: true,
    componentName: 'pages/editor',
  }, {
    path: '/edit/:slug',
    exact: true,
    componentName: 'pages/editor',
  }, {
    path: '/(sign-up|sign-in|sign-out)',
    exact: true,
    componentName: 'pages/login',
  }, {
    path: '/settings',
    exact: true,
    componentName: 'pages/settings',
  }, {
    path: '/([^/]*-[^/]+)',
    exact: true,
    componentName: 'pages/article',
  }, {
    path: '*',
    exact: false,
    componentName: 'components/notFound',
  },
];
