GET http://localhost:8080/api/articles
Accept: application/json
Authorization: Bearer {{JWT}}

###

GET http://localhost:8080/api/articles?limit=-1
Accept: application/json
Authorization: Bearer {{JWT}}

###

GET http://localhost:8080/api/articles/how-to-train-your-dragon
Accept: application/json
Authorization: Bearer {{JWT}}

###

POST http://localhost:8080/api/articles
Accept: application/json
Authorization: Bearer {{JWT}}

{
  "article": {
    "title": "How to train your dragon X",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "dragons"]
  }
}

###

GET http://localhost:8080/api/user
Accept: application/json
Authorization: Bearer {{JWT}}

###

POST http://localhost:8080/api/users
Accept: application/json

{
  "user":{
    "username": "Test",
    "email": "test@test.test",
    "password": "tested"
  }
}

###

POST http://localhost:8080/api/users/login
Accept: application/json

{
  "user":{
    "email": "test@test.test",
    "password": "tested"
  }
}

###

