GET http://localhost:8080/api/articles
Accept: application/json
Authorization: Token {{JWT}}

###

GET http://localhost:8080/api/articles?limit=-1
Accept: application/json
Authorization: Token {{JWT}}

###

GET http://localhost:8080/api/articles/how-to-train-your-dragon-v
Accept: application/json
Authorization: Token {{JWT}}

###

POST http://localhost:8080/api/articles
Accept: application/json
Content-Type: application/json
Authorization: Token {{JWT}}

{
  "article": {
    "title": "How to train your dragon V",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["drogon", "fly"]
  }
}

###

POST http://localhost:8080/api/articles
Accept: application/json
Content-Type: application/json
Authorization: Token {{JWT}}

{
  "article": {
    "title": "How to train your dragon VI",
    "description": "Ever wonder how?",
    "body": "You have to believe"
  }
}

###

PUT http://localhost:8080/api/articles/how-to-train-your-dragon-v
Accept: application/json
Content-Type: application/json
Authorization: Token {{JWT}}

{
  "article": {
    "title": "How to train your dragon VI",
    "description": "changed description",
    "body": "changed body"
  }
}

###

GET http://localhost:8080/api/user
Accept: application/json
Authorization: Token {{JWT}}

###

POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "user":{
    "username": "Test",
    "email": "test@test.test",
    "password": "tested"
  }
}

###

POST http://localhost:8080/api/users/login
Accept: application/json
Content-Type: application/json

{
  "user":{
    "email": "test@test.test",
    "password": "tested"
  }
}

###

PUT http://localhost:8080/api/user
Accept: application/json
Content-Type: application/json
Authorization: Token {{JWT}}

{
  "user":{
    "password": "stolen"
  }
}

###

PUT http://localhost:8080/api/user
Accept: application/json
Content-Type: application/json
Authorization: Token {{JWT}}

{
  "user":{
    "email": "changed@test.test",
    "username": "changed username",
    "password": "changed password",
    "bio": "changed bio"
  }
}