name: Acceptance Localstack Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      localstack:
        env:
          DEBUG: 1
          DOCKER_HOST: unix:///var/run/docker.sock
        image: localstack/localstack:1.4
        ports:
          - '4566:4566'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: realworld
          MYSQL_DATABASE: realworld
          MYSQL_USER: realworld
          MYSQL_PASSWORD: realworld
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/credentials
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - uses: ./.github/actions/npminstall

      - uses: actions/download-artifact@v3
        with:
          name: build

      - working-directory: ./terraform/lambda
        id: terraform
        run: |
          ./localstack.sh
          echo "API_URL=$(terraform output API_URL)" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v6
        with:
          script: |
            core.notice('Check URL ${{ steps.terraform.outputs.API_URL }}')
