name: Continuous Delivery Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  unit:
    uses: ./.github/workflows/unit-tests.yaml

  server-tests:
    needs: [build]
    uses: ./.github/workflows/acceptance-local-tests.yaml

  docker-tests:
    uses: ./.github/workflows/acceptance-docker-tests.yaml

  localstack-tests:
    needs: [build]
    uses: ./.github/workflows/acceptance-localstack-tests.yaml

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy-lambda.yaml
