name: Continuous Delivery Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: actions/checkout@v3

      - run: npm install
      - run: npm run test:unit

      - run: docker-compose up api -d --build

      - run: API_URL=http://localhost:3000/api npx jest acceptance

      - name: Stop containers
        if: always()
        run: docker-compose down
