name: Create branch/PR for schema change

env:
  pscale_base_directory: .pscale

on:
  workflow_dispatch:
    inputs:
      branch:
        description: DB and PR branch name
        required: true
        default: 'add-operation-column-and-index'
      ddl_statements:
        description: 'DDL statements to run in new branch'
        required: true
        default: 'alter table pixel_matrix add column operation varchar(10) default NULL; create index environment_operation on pixel_matrix(environment, operation);'

jobs:
  create_branch_dr_and_pr:
    name: Create branch/PR/DR - click here

    runs-on: ubuntu-latest

    steps:
      - name: Write information about associated PS database entities
        env:
          BRANCH_NAME: ${{ steps.create-db-branch-and-dr.outputs.BRANCH_NAME }}
          DB_NAME: ${{ steps.create-db-branch-and-dr.outputs.DB_NAME }}
          ORG_NAME: ${{ steps.create-db-branch-and-dr.outputs.ORG_NAME }}
          DEPLOY_REQUEST_NUMBER: ${{ steps.create-db-branch-and-dr.outputs.DEPLOY_REQUEST_NUMBER }}
          DEPLOY_REQUEST_URL: ${{ steps.create-db-branch-and-dr.outputs.DEPLOY_REQUEST_URL }}
          BRANCH_URL: ${{ steps.create-db-branch-and-dr.outputs.BRANCH_URL }}
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: |
          mkdir -p ../env/
          envsubst < ps-env-template.sh > ../env/ps-env-${BRANCH_NAME}.sh
          chmod a+x ../env/ps-env-${BRANCH_NAME}.sh
          rm -f typescript
