
on:
  - push
  - pull_request

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      # SET UP
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # BUILD
      - name: Build & Test
        run: .github/pre-push.sh
