name: Continuous Delivery Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  cd:
    permissions:
      id-token: write
      contents: read
    needs: [ci]
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
