name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://hexpm/erlang:23.1.1-alpine-3.12.0
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.0.0
      - run: apk add bash
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: 0.12.0-rc3
      - run: rebar3 install_deps
      - run: rebar3 eunit
      - run: gleam format --check src test
