name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://hexpm/erlang:23.1.1-alpine-3.12.0
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.0.0
      - run: apk add curl tar
      - run: curl -Lo gleam.tar.gz "https://github.com/gleam-lang/gleam/releases/download/v0.12.0-rc3/gleam-v0.12.0-rc3-linux-amd64.tar.gz"
      - run: tar -xf gleam.tar.gz -C .
      - run: rm gleam.tar.gz
      - run: rebar3 install_deps
      - run: rebar3 eunit
      - run: gleam format --check src test
